### PR TITLE
Fix inconsistent latest_block_hash

### PR DESCRIPTION
**Pull request by boundless-forest**
Cherry-pick https://github.com/polkadot-evm/frontier/pull/1424

### CODE REVIEW

**Comment by hackfisher** [comment]
@boundless-forest There are conflicts at, which prevent ci format pass

Diff in /home/runner/work/frontier/frontier/frame/evm/src/tests.rs at line 241:

**Comment by boundless-forest** [comment]
> Diff in /home/runner/work/frontier/frontier/frame/evm/src/tests.rs at line 241:

I'm working on fixinging it (force push to keep the commit history clean). We should respect the CI in this repo in the future, the CI of the branch that we used is not maintained well.

**Comment by acgxv** [comment]
Suggest using the same rust version as darwinia

**Comment by boundless-forest** [comment]
> Suggest using the same rust version as darwinia

nightly-2024-03-17 -> 1.77.0 (darwinia version), but nightly. stable toolchain fails to compile some piece of code.

**Pull request merged**
